<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>fileTypes</key>
		<array>
			<string>abap</string>
			<string>ABAP</string>
		</array>
		<key>foldingStartMarker</key>
		<string>/\*\*|\{\s*$</string>
		<key>foldingStopMarker</key>
		<string>\*\*/|^\s*\}</string>
		<key>keyEquivalent</key>
		<string>^~A</string>
		<key>name</key>
		<string>ABAP</string>
		<key>patterns</key>
		<array>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.comment.abap</string>
					</dict>
				</dict>
				<key>match</key>
				<string>^\*.*\n?</string>
				<key>name</key>
				<string>comment.line.full.abap</string>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.comment.abap</string>
					</dict>
				</dict>
				<key>match</key>
				<string>".*\n?</string>
				<key>name</key>
				<string>comment.line.partial.abap</string>
			</dict>
			<dict>
				<key>match</key>
				<string>(?&lt;![^\s])##.*?(?=([\.:,\s]))</string>
				<key>name</key>
				<string>comment.line.pragma.abap</string>
			</dict>
			<dict>
				<key>match</key>
				<string>(?i)(?&lt;=(?:\s|~|-))(?&lt;=(?:-&gt;|=&gt;))([a-z_\/][a-z_0-9\/]*)(?=\s+(?:=|\+=|-=|\*=|\/=|&amp;&amp;=|&amp;=)\s+)</string>
				<key>name</key>
				<string>variable.other.abap</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b[0-9]+(\b|\.|,)</string>
				<key>name</key>
				<string>constant.numeric.abap</string>
			</dict>
			<dict>
				<key>match</key>
				<string>(?ix)(^|\s+)((PUBLIC|PRIVATE|PROTECTED)\sSECTION)(?=\s+|:|\.)</string>
				<key>name</key>
				<string>storage.modifier.class.abap</string>
			</dict>
			<dict>
				<key>begin</key>
				<string>(?&lt;!\\)(\|)(.*?)</string>
				<key>end</key>
				<string>(?&lt;!\\)(\||(\\\\\|))</string>
				<key>name</key>
				<string>string.interpolated.abap</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>constant.character.escape.abap</string>
					</dict>
				</dict>
				<key>endCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>constant.character.escape.abap</string>
					</dict>
				</dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>({ )|( })</string>
						<key>name</key>
						<string>constant.character.escape</string>
					</dict>
					<dict>
						<key>match</key>
						<string>(?&lt;={ ).*?(?= })</string>
						<key>name</key>
						<string>variable.other.abap</string>
					</dict>
					<dict>
						<key>match</key>
						<string>\\\|</string>
						<key>name</key>
						<string>constant.character.escape.abap</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>begin</key>
				<string>'</string>
				<key>end</key>
				<string>'</string>
				<key>name</key>
				<string>string.quoted.single.abap</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>''</string>
						<key>name</key>
						<string>constant.character.escape.abap</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>begin</key>
				<string>`</string>
				<key>end</key>
				<string>`</string>
				<key>name</key>
				<string>string.quoted.single.abap</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>``</string>
						<key>name</key>
						<string>constant.character.escape.abap</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>begin</key>
				<string>(?i)^\s*(class)\s([a-z_\/][a-z_0-9\/]*)</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>storage.type.block.abap</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>entity.name.type.block.abap</string>
					</dict>
				</dict>
				<key>end</key>
				<string>\s*\.\s*\n?</string>
				<key>name</key>
				<string>meta.block.begin.implementation.abap</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>(?ix)(^|\s+)(definition|implementation|public|inheriting\s+from|final|deferred|abstract|shared\s+memory\s+enabled|(global|local)*\s*friends|(create\s+(public|protected|private))|for\s+behavior\s+of|for\s+testing|risk\s+level\s+(critical|dangerous|harmless))|duration\s(short|medium|long)(?=\s+|\.)</string>
						<key>name</key>
						<string>storage.modifier.class.abap</string>
					</dict>
					<dict>
						<key>begin</key>
						<string>(?=[A-Za-z_][A-Za-z0-9_]*)</string>
						<key>contentName</key>
						<string>entity.name.type.block.abap</string>
						<key>end</key>
						<string>(?![A-Za-z0-9_])</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#generic_names</string>
							</dict>
						</array>
					</dict>
				</array>
			</dict>
			<dict>
				<key>begin</key>
				<string>(?ix)^\s*(method)\s(?:([a-z_\/][a-z_0-9\/]*)~)?([a-z_\/][a-z_0-9\/]*)</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>storage.type.block.abap</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>entity.name.type.abap</string>
					</dict>
					<key>3</key>
					<dict>
						<key>name</key>
						<string>entity.name.function.abap</string>
					</dict>
				</dict>
				<key>end</key>
				<string>\s*\.\s*\n?</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>(?ix)(?&lt;=^|\s)(BY\s+DATABASE(\s+PROCEDURE|\s+FUNCTION|\s+GRAPH\s+WORKSPACE)|BY\s+KERNEL\s+MODULE)(?=\s+|\.)</string>
						<key>name</key>
						<string>storage.modifier.method.abap</string>
					</dict>
					<dict>
						<key>match</key>
						<string>(?ix)(?&lt;=^|\s)(FOR\s+(HDB|LLANG))(?=\s+|\.)</string>
						<key>name</key>
						<string>storage.modifier.method.abap</string>
					</dict>
					<dict>
						<key>match</key>
						<string>(?ix)(?&lt;=\s)(OPTIONS\s+(READ-ONLY|DETERMINISTIC|SUPPRESS\s+SYNTAX\s+ERRORS))(?=\s+|\.)</string>
						<key>name</key>
						<string>storage.modifier.method.abap</string>
					</dict>
					<dict>
						<key>match</key>
						<string>(?ix)(?&lt;=^|\s)(LANGUAGE\s+(SQLSCRIPT|SQL|GRAPH))(?=\s+|\.)</string>
						<key>name</key>
						<string>storage.modifier.method.abap</string>
					</dict>
					<dict>
						<key>match</key>
						<string>(?ix)(?&lt;=\s)(USING)\s+([a-z_\/][a-z_0-9\/=\&gt;]*)+(?=\s+|\.)</string>
						<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>storage.modifier.method.abap</string>
							</dict>
						</dict>
					</dict>
					<dict>
						<key>begin</key>
						<string>(?=[A-Za-z_][A-Za-z0-9_]*)</string>
						<key>end</key>
						<string>(?![A-Za-z0-9_])</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#generic_names</string>
							</dict>
						</array>
					</dict>
				</array>
			</dict>
			<dict>
				<key>begin</key>
				<string>(?ix)^\s*(INTERFACE)\s([a-z_\/][a-z_0-9\/]*)</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>storage.type.block.abap</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>entity.name.type.abap</string>
					</dict>
				</dict>
				<key>end</key>
				<string>\s*\.\s*\n?</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>(?ix)(?&lt;=^|\s)(DEFERRED|PUBLIC)(?=\s+|\.)</string>
						<key>name</key>
						<string>storage.modifier.method.abap</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>begin</key>
				<string>(?ix)^\s*(FORM)\s([a-z_\/][a-z_0-9\/\-\?]*)</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>storage.type.block.abap</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>entity.name.type.abap</string>
					</dict>
				</dict>
				<key>end</key>
				<string>\s*\.\s*\n?</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>(?ix)(?&lt;=^|\s)(USING|TABLES|CHANGING|RAISING|IMPLEMENTATION|DEFINITION)(?=\s+|\.)</string>
						<key>name</key>
						<string>storage.modifier.form.abap</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#abaptypes</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#keywords_followed_by_braces</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>match</key>
				<string>(?i)(endclass|endmethod|endform|endinterface)</string>
				<key>name</key>
				<string>storage.type.block.end.abap</string>
			</dict>
			<dict>
				<key>match</key>
				<string>(?i)(&lt;[A-Za-z_][A-Za-z0-9_]*&gt;)</string>
				<key>name</key>
				<string>variable.other.field.symbol.abap</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#keywords</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#abap_constants</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#reserved_names</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#operators</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#builtin_functions</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#abaptypes</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#system_fields</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#sql_functions</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#sql_types</string>
			</dict>
		</array>
		<key>repository</key>
		<dict>
			<key>abap_constants</key>
			<dict>
				<key>match</key>
				<string>(?ix)(?&lt;=\s)(initial|null|@?space|@?abap_true|@?abap_false|@?abap_undefined|table_line|
                                %_final|%_hints|%_predefined|col_background|col_group|col_heading|col_key|col_negative|col_normal|col_positive|col_total|
				adabas|as400|db2|db6|hdb|oracle|sybase|mssqlnt|pos_low|pos_high)(?=\s|\.|,)</string>
				<key>name</key>
				<string>constant.language.abap</string>
			</dict>
			<key>reserved_names</key>
			<dict>
				<key>match</key>
				<string>(?ix)(?&lt;=\s)(me|super)(?=\s|\.|,|-&gt;)</string>
				<key>name</key>
				<string>constant.language.abap</string>
			</dict>
			<key>abaptypes</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>(?ix)\s(abap_bool|string|xstring|any|clike|csequence|numeric|xsequence|decfloat|decfloat16|decfloat34|utclong|simple|int8|c|n|i|p|f|d|t|x)(?=\s|\.|,)</string>
						<key>name</key>
						<string>support.type.abap</string>
					</dict>
					<dict>
						<key>match</key>
						<string>(?ix)\s(TYPE|REF|TO|LIKE|LINE|OF|STRUCTURE|STANDARD|SORTED|HASHED|INDEX|TABLE|WITH|UNIQUE|NON-UNIQUE|SECONDARY|DEFAULT|KEY)(?=\s|\.|,)</string>
						<key>name</key>
						<string>keyword.control.simple.abap</string>
					</dict>
				</array>
			</dict>
			<key>arithmetic_operator</key>
			<dict>
				<key>match</key>
				<string>(?i)(?&lt;=\s)(\+|\-|\*|\*\*|\/|%|DIV|MOD|BIT-AND|BIT-OR|BIT-XOR|BIT-NOT)(?=\s)</string>
				<key>name</key>
				<string>keyword.control.simple.abap</string>
			</dict>
			<key>comparison_operator</key>
			<dict>
				<key>match</key>
				<string>(?i)(?&lt;=\s)(&lt;|&gt;|&lt;\=|&gt;\=|\=|&lt;&gt;|eq|ne|lt|le|gt|ge|cs|cp|co|cn|ca|na|ns|np|byte-co|byte-cn|byte-ca|byte-na|byte-cs|byte-ns|o|z|m)(?=\s)</string>
				<key>name</key>
				<string>keyword.control.simple.abap</string>
			</dict>
			<key>control_keywords</key>
			<dict>
				<key>match</key>
				<string>(?ix)(^|\s)(
	        at|case|catch|continue|do|elseif|else|endat|endcase|endcatch|enddo|endif|
	        endloop|endon|endtry|endwhile|if|loop|on|raise|try|while)(?=\s|\.|:)</string>
				<key>name</key>
				<string>keyword.control.flow.abap</string>
			</dict>
			<key>generic_names</key>
			<dict>
				<key>match</key>
				<string>[A-Za-z_][A-Za-z0-9_]*</string>
			</dict>
			<key>keywords</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#main_keywords</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#text_symbols</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#control_keywords</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#keywords_followed_by_braces</string>
					</dict>
				</array>
			</dict>
			<key>logical_operator</key>
			<dict>
				<key>match</key>
				<string>(?i)(?&lt;=\s)(not|or|and)(?=\s)</string>
				<key>name</key>
				<string>keyword.control.simple.abap</string>
			</dict>
			<key>system_fields</key>
			<dict>
				<key>match</key>
				<string>(?ix)\b(sy)-(abcde|batch|binpt|calld|callr|colno|cpage|cprog|cucol|curow|datar|datlo|datum|dayst|dbcnt|dbnam|dbsysc|dyngr|dynnr|fdayw|fdpos|host|index|langu|ldbpg|lilli|linct|linno|linsz|lisel|listi|loopc|lsind|macol|mandt|marow|modno|msgid|msgli|msgno|msgty|msgv[1-4]|opsysc|pagno|pfkey|repid|saprl|scols|slset|spono|srows|staco|staro|stepl|subrc|sysid|tabix|tcode|tfill|timlo|title|tleng|tvar[0-9]|tzone|ucomm|uline|uname|uzeit|vline|wtitl|zonlo)(?=\.|\s)</string>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>variable.language.abap</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>variable.language.abap</string>
					</dict>
				</dict>
			</dict>
			<key>main_keywords</key>
			<dict>
				<key>match</key>
				<string>(?ix)(?&lt;=^|\s)(
abap-source|
abbreviated|
abstract|
accepting|
accept|
access|
according|
action|
activation|
actual|
add-corresponding|
add|
adjacent|
after|
aliases|
alias|
align|
allocate|
all|
alpha|
amdp|
analysis|
analyzer|
appending|
append|
application|
archive|
area|
arithmetic|
ascending|
assert|
assigned|
assigning|
assign|
association|
asynchronous|
as|
attributes|
at|
authority-check|
authority|
authorization|
auto|
background|
backup|
backward|
back|
badi|
base|
before|
begin|
behavior|
between|
binary|
bit|
blanks|
blank|
blocks|
block|
boundaries|
bounds|
bound|
boxed|
break-point|
break|
buffer|
bypassing|
byte-order|
byte|
by|
calling|
call|
casting|
cast|
cds|
centered|
center|
chain-input|
chain-request|
chain|
change|
changing|
channels|
char-to-hex|
character|
checkbox|
check|
cid|
circular|
class-data|
class-events|
class-methods|
class-method|
class-pool|
class|
cleanup|
clear|
clients|
client|
clock|
clone|
close|
cnt|
code|
collect|
color|
column|
comments|
comment|
commit|
common|
communication|
comparing|
components|
component|
compression|
compute|
concatenate|
condense|
condition|
cond|
connection|
constants|
constant|
contexts|
context|
controls|
control|
conversion|
convert|
conv|
copy|
corresponding|
country|
count|
cover|
create|
currency|
current|
cursor-selection|
cursor|
customer-function|
customer|
database|
datainfo|
dataset|
data|
date|
daylight|
ddl|
deallocate|
decimals|
declarations|
deep|
default|
deferred|
define|
defining|
delete|
deleting|
demand|
descending|
describe|
destination|
detail|
determine|
dialog|
did|
directory|
discarding|
display-mode|
display|
distance|
distinct|
divide-corresponding|
divide|
dummy|
duplicates|
duplicate|
duration|
during|
dynamic|
dynpro|
editor-call|
edit|
empty|
enabled|
enabling|
encoding|
end-enhancement-section|
end-of-definition|
end-of-editing|
end-of-page|
end-of-selection|
end-test-injection|
end-test-seam|
endchain|
endenhancement|
endexec|
endfunction|
endian|
ending|
endmodule|
endprovide|
endselect|
endwith|
end|
engineering|
enhancement-point|
enhancement-section|
enhancements|
enhancement|
entities|
entity|
entries|
entry|
enum|
environment|
equiv|
errormessage|
errors|
escape|
escaping|
events|
event|
exact|
exception-table|
exceptions|
exception|
except|
exclude|
excluding|
execute|
exec|
exists|
exit-command|
exit|
expanding|
explicit|
exponent|
exporting|
export|
extended|
extension|
extract|
failed|
fail|
features|
fetch|
field-groups|
field-symbols|
fields|
field|
file|
fill|
filters|
filter|
final|
find|
first-line|
first|
fixed-point|
flush|
following|
format|
forward|
for|
found|
frames|
frame|
free|
from|
full|
function-pool|
function|
generate|
get|
giving|
graph|
groups|
group|
handler|
handle|
hashed|
having|
headers|
header|
heading|
help-id|
help-request|
hide|
high|
hint|
hold|
hotspot|
icon|
identification|
identifier|
ids|
id|
ignore|
ignoring|
immediately|
implemented|
implicit|
importing|
import|
inactive|
includes|
include|
including|
incl|
increment|
index-line|
index|
indicators|
infotypes|
inheriting|
initialization|
initial|
init|
inner|
input|
insert|
instances|
instance|
intensified|
interface-pool|
interfaces|
interface|
internal|
intervals|
into|
inverse|
inverted-date|
in|
iso|
is|
job|
join|
keeping|
keep|
kernel|
keys|
keywords|
key|
kind|
language|
last|
late|
layout|
leading|
leave|
left-justified|
leftplus|
leftspace|
left|
legacy|
length|
let|
levels|
level|
like|
line-count|
line-selection|
line-size|
linefeed|
lines|
line|
link|
list-processing|
listbox|
list|
load-of-program|
load|
locale|
local|
locks|
lock|
log-point|
logical|
lower|
low|
main|
mapped|
mapping|
margin|
mark|
mask|
matchcode|
match|
maximum|
members|
memory|
mesh|
message-id|
messages|
message|
messaging|
methods|
method|
minimum|
mode|
modifier|
modify|
modif|
module|
move-corresponding|
move|
multiply-corresponding|
multiply|
nametab|
name|
native|
nested|
nesting|
new-line|
new-page|
new-section|
new|
next|
no-display|
no-extension|
no-gaps|
no-gap|
no-grouping|
no-heading|
no-scrolling|
no-sign|
no-title|
no-zero|
nodes|
node|
non-unicode|
non-unique|
no|
number|
objects|
object|
objmgr|
obligatory|
occurences|
occurence|
occurrences|
occurrence|
occurs|
offset|
of|
only|
on|
open|
optional|
options|
option|
order|
others|
outer|
output-length|
output|
out|
overflow|
overlay|
package|
pack|
padding|
pad|
page|
parameter-table|
parameters|
parameter|
partially|
part|
pattern|
pcre|
percentage|
performing|
perform|
permissions|
pf-status|
pf01|
pf02|
pf03|
pf04|
pf05|
pf06|
pf07|
pf08|
pf09|
pf10|
pf11|
pf12|
pf13|
pf14|
pf15|
pf16|
pf17|
pf18|
pf19|
pf20|
pf21|
pf22|
pf23|
pf24|
places|
pool|
position|
pragmas|
preceding|
precompiled|
preferred|
preserving|
primary|
print-control|
print|
private|
privileged|
procedure|
process|
program|
property|
protected|
provide|
pushbutton|
push|
put|
query|
queue-only|
queueonly|
quickinfo|
radiobutton|
raising|
ranges|
range|
read-only|
read|
received|
receive|
receiving|
redefinition|
reduce|
reference|
refresh|
ref|
regex|
reject|
renaming|
replacement|
replace|
replacing|
reported|
report|
requested|
request|
required|
reserve|
reset|
resolution|
respecting|
response|
restore|
results|
result|
resumable|
resume|
retry|
returning|
return|
right-justified|
rightplus|
rightspace|
right|
rollback|
rows|
row|
rp-provide-from-last|
run|
sap-spool|
sap|
save|
saving|
scale_preserving_scientific|
scale_preserving|
scan|
scientific_with_leading_zero|
scientific|
screen|
scroll-boundary|
scrolling|
scroll|
search|
seconds|
section|
select-options|
selection-screen|
selection-sets|
selection-set|
selection-table|
selections|
selection|
select|
send|
separated|
separate|
session|
set|
shared|
shift|
shortdump-id|
shortdump|
sign_as_postfix|
sign|
simple|
simulation|
single|
size|
skipping|
skip|
smart|
some|
sortable|
sorted|
sort|
source|
specified|
split|
spool|
spots|
sql|
stable|
stamp|
standard|
start-of-editing|
start-of-selection|
starting|
statements|
statement|
state|
statics|
static|
statusinfo|
step-loop|
step|
stop|
structures|
structure|
style|
subkey|
submatches|
submit|
subroutine|
subscreen|
substring|
subtract-corresponding|
subtract|
suffix|
summary|
summing|
sum|
supplied|
supply|
suppress|
switch|
symbol|
syntax-check|
syntax-trace|
system-call|
system-exceptions|
tabbed|
tables|
tableview|
table|
tabstrip|
tab|
target|
tasks|
task|
test-injection|
test-seam|
testing|
test|
textpool|
text|
then|
throw|
timestamp|
times|
timezone|
time|
titlebar|
title|
tokens|
top-lines|
top-of-page|
to|
trace-file|
trace-table|
trailing|
transaction|
transfer|
transformation|
translate|
transporting|
trmac|
truncate|
truncation|
type-pools|
type-pool|
types|
type|
uline|
unassign|
unbounded|
under|
unicode|
union|
unique|
unit|
unix|
unpack|
until|
unwind|
update|
upper|
up|
user-command|
user|
using|
utf-8|
uuid|
validate|
valid|
value-request|
values|
value|
varying|
vary|
version|
via|
visible|
wait|
warning|
whenever|
when|
where|
width|
windows|
window|
with-heading|
with-title|
without|
with|
word|
workspace|
work|
write|
xml|
xsd|
yes|
zero|
zone
		        	)(?=\s|\.|:|,)</string>
				<key>name</key>
				<string>keyword.control.simple.abap</string>
			</dict>
			<key>text_symbols</key>
			<dict>
				<key>match</key>
				<string>(?ix)(?&lt;=^|\s)(text)-([A-Z0-9]{1,3})(?=\s|\.|:|,)</string>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.control.simple.abap</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>constant.numeric.abap</string>
					</dict>
				</dict>
			</dict>
			<key>keywords_followed_by_braces</key>
			<dict>
				<key>match</key>
				<string>(?ix)\b(data|value|field-symbol|final|reference|resumable)\((&lt;?[a-z_\/][a-z_0-9\/]*&gt;?)\)</string> 
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.control.simple.abap</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>variable.other.abap</string>
					</dict>
				</dict>
			</dict>
			<key>operators</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#other_operator</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#arithmetic_operator</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#comparison_operator</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#logical_operator</string>
					</dict>
				</array>
			</dict>
			<key>other_operator</key>
			<dict>
				<key>match</key>
				<string>(?&lt;=\s)(&amp;&amp;|&amp;|\?=|\+=|-=|\/=|\*=|&amp;&amp;=|&amp;=)(?=\s)</string>
				<key>name</key>
				<string>keyword.control.simple.abap</string>
			</dict>
			<key>builtin_functions</key>
			<dict>
				<key>match</key>
				<string>(?ix)(?&lt;=\s)(abs|sign|ceil|floor|trunc|frac|acos|asin|atan|cos|sin|tan|cosh|sinh|tanh|exp|log|log10|sqrt|strlen|xstrlen|charlen|lines|numofchar|dbmaxlen|round|rescale|nmax|nmin|cmax|cmin|boolc|boolx|xsdbool|contains|contains_any_of|contains_any_not_of|matches|line_exists|ipow|char_off|count|count_any_of|count_any_not_of|distance|condense|concat_lines_of|escape|find|find_end|find_any_of|find_any_not_of|insert|match|repeat|replace|reverse|segment|shift_left|shift_right|substring|substring_after|substring_from|substring_before|substring_to|to_upper|to_lower|to_mixed|from_mixed|translate|bit-set|line_index)(?=\()</string>
				<key>name</key>
				<string>entity.name.function.builtin.abap</string>
			</dict>
			<key>sql_types</key>
			<dict>
				<key>match</key>
				<string>(?ix)(?&lt;=\s)(char|clnt|cuky|curr|datn|dats|dec|decfloat16|decfloat34|fltp|int1|int2|int4|int8|lang|numc|quan|raw|sstring|timn|tims|unit|utclong)(?=\s|\(|\))</string>
				<key>name</key>
				<string>entity.name.type.sql.abap</string>
			</dict>
			<key>sql_functions</key>
			<dict>
				<key>match</key>
				<string>(?ix)(?&lt;=\s)(
abap_system_timezone|
abap_user_timezone|
abs|
add_days|
add_months|
allow_precision_loss|
as_geo_json|
avg|
bintohex|
cast|
ceil|
coalesce|
concat_with_space|
concat|
corr_spearman|
corr|
count|
currency_conversion|
datn_add_days|
datn_add_months|
datn_days_between|
dats_add_days|
dats_add_months|
dats_days_between|
dats_from_datn|
dats_is_valid|
dats_tims_to_tstmp|
dats_to_datn|
dayname|
days_between|
dense_rank|
division|
div|
extract_day|
extract_hour|
extract_minute|
extract_month|
extract_second|
extract_year|
first_value|
floor|
grouping|
hextobin|
initcap|
instr|
is_valid|
lag|
last_value|
lead|
left|
length|
like_regexpr|
locate_regexpr_after|
locate_regexpr|
locate|
lower|
lpad|
ltrim|
max|
median|
min|
mod|
monthname|
ntile|
occurrences_regexpr|
over|
product|
rank|
replace_regexpr|
replace|
rigth|
round|
row_number|
rpad|
rtrim|
stddev|
string_agg|
substring_regexpr|
substring|
sum|
tims_from_timn|
tims_is_valid|
tims_to_timn|
to_blob|
to_clob|
tstmp_add_seconds|
tstmp_current_utctimestamp|
tstmp_is_valid|
tstmp_seconds_between|
tstmp_to_dats|
tstmp_to_dst|
tstmp_to_tims|
tstmpl_from_utcl|
tstmpl_to_utcl|
unit_conversion|
upper|
utcl_add_seconds|
utcl_current|
utcl_seconds_between|
uuid|
var|
weekday
                                )(?=\()</string>
				<key>name</key>
				<string>entity.name.function.sql.abap</string>
			</dict>
		</dict>
		<key>scopeName</key>
		<string>source.abap</string>
		<key>uuid</key>
		<string>0357FFB4-EFFF-4DE9-8371-B0F9C8DF1B21</string>
	</dict>
</plist>
